version: "3.9"

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: mtogo
      POSTGRES_PASSWORD: mtogo
      POSTGRES_DB: mtogo
    networks: [mtogo]
    ports:
      - "55433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    networks: [mtogo]
    ports:
      - "5672:5672"
      - "15672:15672"

  legacy-menu:
    image: mtogo/legacy-menu:local
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Db: Host=postgres;Port=5432;Database=mtogo;Username=mtogo;Password=mtogo
    networks: [mtogo]
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  ordering:
    image: mtogo/ordering:local
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      LegacyMenu__BaseUrl: http://legacy-menu:8080
      RabbitMq__Host: rabbitmq
    networks: [mtogo]
    depends_on:
      - rabbitmq
      - legacy-menu
    deploy:
      replicas: 2
    ports:
      - "8082:8080"

  gateway:
    image: mtogo/gateway:local
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
    networks: [mtogo]
    depends_on:
      - legacy-menu
      - ordering
    ports:
      - "8080:8080"

networks:
  mtogo:
    driver: overlay
