services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: mtogo
      POSTGRES_PASSWORD: mtogo
      POSTGRES_DB: mtogo
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  legacy-menu:
    build:
      context: ../../
      dockerfile: src/legacy-menu/Mtogo.LegacyMenu.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Db: Host=postgres;Port=5432;Database=mtogo;Username=mtogo;Password=mtogo
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  ordering:
    build:
      context: ../../
      dockerfile: src/services/ordering/Mtogo.Ordering.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      LegacyMenu__BaseUrl: http://legacy-menu:8080
      RabbitMq__Host: rabbitmq
    depends_on:
      - rabbitmq
      - legacy-menu
    ports:
      - "8082:8080"

  gateway:
    build:
      context: ../../
      dockerfile: src/gateway/Mtogo.Gateway.Yarp/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
    depends_on:
      - legacy-menu
      - ordering
    ports:
      - "8080:8080"
