global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "ordering"
    metrics_path: /metrics
    static_configs:
      - targets: ["ordering:8080"]

  - job_name: "legacy-menu"
    metrics_path: /metrics
    static_configs:
      - targets: ["legacy-menu:8080"]
